node:
  switch01:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
    switching:
      interface:
        members:
        mode:
        vlans:
    routing:
      lo: 10.1.1.1/32
      ospf:
        area: 0
        neighbors:
          - swp1
          - swp2
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
  switch02:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
    switching:
      interface:
    routing:
      lo: 10.2.2.2/32
      ospf:
        area: 0
        neighbors:
          - swp1
          - swp2
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
